package generator

const metamodelTemplate = `// Code generated by metamodel. DO NOT EDIT.
// Author: namnv2496

package {{.PackageName}}
{{range .Structs}}
// {{.StructName}}_ contains field name constants for {{.StructName}}
var {{.StructName}}_ = struct {
	TableName string
	TableNames string
{{- range .Fields}}
	{{.FieldName}} Field
{{- end}}
}{
	TableName: "{{snakeCase .StructName}}",
	TableNames: "{{snakeCase .StructName}}s", // table name with 's'

{{- range .Fields}}
	{{.FieldName}}: "{{.TagName}}",
{{- end}}
}
{{end}}
`

const commonTemplate = `// Code generated by metamodel. DO NOT EDIT.

package {{.PackageName}}

const (
	Comma      string = ", "
	ON		   string = " ON "
	JOIN       string = " join "
	INNER_JOIN string = " inner join "
)
`

const gormFieldTemplate = `// Code generated by metamodel. DO NOT EDIT.

package {{.PackageName}}

import (
	"fmt"
	"strings"
	"gorm.io/gorm/clause"
)

// Field represents a database column name with GORM query builder methods.
type Field string

// Equal generates a GORM equality condition: "column = ?"
func (f Field) Equal(val any) clause.Eq {
	return clause.Eq{Column: string(f), Value: val}
}

func (f Field) EqualString(val any) string {
	return fmt.Sprintf(" %s = %v ", string(f), val)
}

// NotEqual generates a GORM not-equal condition: "column <> ?"
func (f Field) NotEqual(val any) clause.Neq {
	return clause.Neq{Column: string(f), Value: val}
}

func (f Field) NotEqualString(val any) string {
	return fmt.Sprintf(" %s <> %v ", string(f), val)
}

// In generates a GORM IN condition: "column IN (?)"
func (f Field) In(vals ...any) clause.IN {
	return clause.IN{Column: clause.Column{Name: string(f)}, Values: vals}
}

func (f Field) InString(vals ...any) string {
	var valStrs []string
	for _, v := range vals {
		valStrs = append(valStrs, fmt.Sprintf("%s", v))
	}
	return fmt.Sprintf(" %s IN (%s) ", string(f), strings.Join(valStrs, ", "))
}

// Gt generates a GORM greater-than condition: "column > ?"
func (f Field) Gt(val any) clause.Gt {
	return clause.Gt{Column: string(f), Value: val}
}

func (f Field) GtString(val any) string {
	return fmt.Sprintf(" %s > %v ", string(f), val)
}

// Gte generates a GORM greater-than-or-equal condition: "column >= ?"
func (f Field) Gte(val any) clause.Gte {
	return clause.Gte{Column: string(f), Value: val}
}

func (f Field) GteString(val any) string {
	return fmt.Sprintf(" %s >= %v ", string(f), val)
}

// Lt generates a GORM less-than condition: "column < ?"
func (f Field) Lt(val any) clause.Lt {
	return clause.Lt{Column: string(f), Value: val}
}

func (f Field) LtString(val any) string {
	return fmt.Sprintf(" %s < %v ", string(f), val)
}

// Lte generates a GORM less-than-or-equal condition: "column <= ?"
func (f Field) Lte(val any) clause.Lte {
	return clause.Lte{Column: string(f), Value: val}
}

func (f Field) LteString(val any) string {
	return fmt.Sprintf(" %s <= %v ", string(f), val)
}

// IsTrue generates a GORM equality condition for boolean true.
func (f Field) IsTrue() clause.Eq {
	return clause.Eq{Column: string(f), Value: true}
}

func (f Field) IsTrueString() string {
	return fmt.Sprintf(" %s = true ", string(f))
}

// IsFalse generates a GORM equality condition for boolean false.
func (f Field) IsFalse() clause.Eq {
	return clause.Eq{Column: string(f), Value: false}
}

func (f Field) IsFalseString() string {
	return fmt.Sprintf(" %s = false ", string(f))
}

// Asc returns an ORDER BY ascending expression.
func (f Field) Asc() clause.OrderByColumn {
	return clause.OrderByColumn{Column: clause.Column{Name: string(f)}}
}

func (f Field) AscString() string {
	return fmt.Sprintf(" %s ASC ", string(f))
}

// Desc returns an ORDER BY descending expression.
func (f Field) Desc() clause.OrderByColumn {
	return clause.OrderByColumn{Column: clause.Column{Name: string(f)}, Desc: true}
}

func (f Field) DescString() string {
	return fmt.Sprintf(" %s DESC ", string(f))
}

// String returns the raw column name.
func (f Field) String() string {
	return string(f)
}

func (f Field) As(val any) string {
	return fmt.Sprintf(" %s as %v ", string(f), val)
}
`
