spring:
  datasource:
    url: 'jdbc:oracle:thin:@//localhost:1521/oracleinanutshell/oracle-xe-11g'
    username: books
    password: books
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      minimumIdle: '5'
      maximumPoolSize: '20'
      idleTimeout: '30000'
      maxLifetime: '2000000'
      connectionTimeout: '30000'
      poolName: HikariPoolBooks
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none
